[package]
name = "microduck_runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
rustypot = "1.4.2"
ort = "2.0.0-rc.11"
anyhow = "1.0"
ctrlc = "3.4"
serialport = "4.8"
clap = { version = "4.5", features = ["derive"] }
openssl = { version = "0.10", features = ["vendored"] }
