[package]
name = "microduck_runtime"
version = "0.1.0"
edition = "2021"

[lib]
name = "microduck_runtime"
path = "src/lib.rs"

[[bin]]
name = "microduck_runtime"
path = "src/main.rs"

[[bin]]
name = "test_imu"
path = "examples/test_imu.rs"

[[bin]]
name = "test_i2c_raw"
path = "examples/test_i2c_raw.rs"

[dependencies]
rustypot = "1.4.2"
ort = { version = "2.0.0-rc.11", features = ["load-dynamic"] }
anyhow = "1.0"
ctrlc = "3.4"
serialport = "4.8"
clap = { version = "4.5", features = ["derive"] }
openssl = "0.10"
libc = "0.2"
ndarray = "0.15"
