[package]
name = "microduck_runtime"
version = "0.1.0"
edition = "2021"

[lib]
name = "microduck_runtime"
path = "src/lib.rs"

[[bin]]
name = "microduck_runtime"
path = "src/main.rs"

[dependencies]
rustypot = "1.4.2"
ort = "2.0.0-rc.11"
anyhow = "1.0"
ctrlc = "3.4"
serialport = "4.8"
clap = { version = "4.5", features = ["derive"] }
openssl = { version = "0.10", features = ["vendored"] }
openssl-sys = { version = "0.9", features = ["vendored"] }
bno055 = "0.4"
linux-embedded-hal = "0.4"
